config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'directory#index'

  get 'search/:keyword(.:format)' => 'books#search', as: 'search/'

  get 'genre_search/:keyword(.:format)' => 'books#genre_search', as: 'genre_search//'

  get 'books/ranking' => 'books#ranking'
  
  post 'rent' => 'transactions#rent'

  resources :books

  resources :authors

  resources :transactions

  resources :statuses

  resources :publishers

  resources :genres

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @statuses }
      format.json  { render :json => @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name)
    end

    def authenticate
      if !current_user.try(:admin?)
        flash[:error] = "You don't have a permission!"
        redirect_to :root
      end
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status, html: { class: 'form-vertical'}) do |f| %>
  <fieldset>
    <% if @status.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

        <ul>
        <% @status.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="controller-group">
      <%= f.label :name %>
      <div class='controls'>
        <%= f.text_field :name, class: 'form-control' %><br />
      </div>
    </div>
    <div class="form-actions clearfix">
      <span class='pull-right'>
        <%= link_to 'Back', statuses_path, class: 'btn btn-default' %>
        <%= f.submit class: 'btn btn-primary' %>
      </span>
    </div>
  </fieldset>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

app/views/statuses/index.html.erb
<h1>Listing statuses 
  <% if current_user.try(:admin?) %>
    <a href='/statuses/new' class='btn btn-default btn-sm pull-right'><span class='glyphicon glyphicon-plus'></span>&nbsp;New status</a>
  <% end %>
</h1>

<ul class='main-list well'>
  <% if @statuses.count == 0 %>
    <li class='row-fluid'>
      <div class='myicon'><span class='glyphicon glyphicon-info-sign red'></span>&nbsp;&nbsp;No records found</div>
    </li>
  <% end %>
  <% @statuses.each do |status| %>
    <li class='row-fluid'>
      <div class='myicon'><%= status.name %></div>
      <div class='pull-right'>
        <a href="<%= status_path(status) %>" class='btn btn-xs' role='button'><span class='glyphicon glyphicon-zoom-in'></span></a>
        <% if current_user.try(:admin?) %>
          <a href="<%= edit_status_path(status) %>" class='btn btn-xs'  role='button'><span class='glyphicon glyphicon-edit'></span></a>
          <a href="<%= status_path(status) %>" class='btn btn-xs btn-danger  role='button'' data-confirm'Are you sure?' data-method='delete' rel='nofollow'><span class='glyphicon glyphicon-remove'></span></a>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

app/views/statuses/show.html.erb
<h1><%= @status.name %>
	<small class='pull-right'>
		<% if current_user.try(:admin?) %>
			<%= link_to 'Edit', edit_status_path(@status), class: 'btn btn-primary' %>
		<% end %>
		<%= link_to "Back", statuses_path, class: 'btn btn-default' %>
	</small>
</h1>