config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'directory#index'

  get 'search/:keyword(.:format)' => 'books#search', as: 'search/'

  get 'genre_search/:keyword(.:format)' => 'books#genre_search', as: 'genre_search//'

  get 'books/ranking' => 'books#ranking'
  
  post 'rent' => 'transactions#rent'

  resources :books

  resources :authors

  resources :transactions

  resources :statuses

  resources :publishers

  resources :genres

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate, except: [:index, :show, :rent]
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /transactions
  # GET /transactions.json
  def index
    if current_user.try(:admin?)
      @transactions = Transaction.all.order(issue_date: :desc)
    else
      @transactions = Transaction.all.where("user_id =?", current_user.id).order(issue_date: :desc)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions.to_xml(:include => [:book, :user, :status]) }
      format.json  { render :json => @transactions.to_json(:include => [:book, :user, :status]) }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions.to_xml(:include => [:book, :user, :status]) }
      format.json  { render :json => @transactions.to_json(:include => [:book, :user, :status]) }
    end
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.status_id < 7 # Created Transaction's Book is not returned
      validate_book
      validate_user

      book = Book.where(id: transaction_params[:book_id]).first
      book.decrement!(:remaining)
      user = User.where(id: transaction_params[:user_id]).first
      user.increment!(:borrowed)
    end

    respond_to do |format|
      if @transaction.save        
        book.increment!(:popularity)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        if @transaction.status_id = '7' # Book is returned
          book = Book.where(id: transaction_params[:book_id]).first
          book.increment!(:remaining)
          user = User.where(id: transaction_params[:user_id]).first
          user.decrement!(:borrowed)
        end
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    if @transaction.status_id != '7' # Book is returned
      user = User.where(id: @transaction.user_id).first
      user.decrement!(:borrowed)
    end

    Book.where(id: @transaction.book_id).first.increment!(:remaining)
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def rent
    is_book_valid = validate_book
    is_user_valid = validate_user

    if is_book_valid == false && is_user_valid == false
      errors = ['This book is not available!', 'You have reached a limit for borrowing books.']
      flash[:error] = errors.join("<br/>").html_safe
    elsif is_book_valid == false
      flash[:error] = "This book is not available!"
    elsif is_user_valid == false
      flash[:error] = "You have reached a limit for borrowing books."
    end

    if is_book_valid == true && is_user_valid == true
      @transaction = Transaction.new(transaction_params)
      @transaction.staff_id = '1'
      @transaction.status_id = '1' # Waiting for payment
      today = Time.now
      @transaction.issue_date = today.strftime("%Y-%m-%d")
      @transaction.due_date = (today + 10.day).strftime("%Y-%m-%d")

      respond_to do |format|
        if @transaction.save
          book = Book.where(id: transaction_params[:book_id]).first
          book.decrement!(:remaining)
          book.increment!(:popularity)
          user = User.where(id: transaction_params[:user_id]).first
          user.increment!(:borrowed)
          flash[:notice] = "Transaction was successfully created."
          format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
          format.json { render :show, status: :created, location: @transaction }
        else
          format.html { render :new }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:book_id, :user_id, :staff_id, :status_id, :issue_date, :due_date)
    end

    def authenticate
      if !current_user.try(:admin?)
        flash[:error] = "You don't have a permission!"
        redirect_to :root
      end
    end

    def validate_book
      book_check = Book.where(id: transaction_params[:book_id]).first
      if (book_check.remaining == 0)
        return false
      else
        return true
      end
    end

    def validate_user
      user_check = User.where(id: transaction_params[:user_id]).first
      if (user_check.increment(:borrowed).borrowed > user_check.max_book)
        return false
      else
        return true
      end
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction, html: { class: 'form-vertical'}) do |f| %>
  <fieldset>
    <% if @transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

        <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="controller-group">
      <%= f.label :book_id %>
      <div class='controls'>
        <%= f.collection_select :book_id, Book.all, :id, :title, { prompt: "Select a category" }, { class: "form-control" } %><br />
      </div>
    </div>
    <div class="controller-group">
      <%= f.label :user_id %>
      <div class='controls'>
        <%= f.collection_select :user_id, User.all, :id, :name, { prompt: "Select a category" }, {class: "form-control" } %><br />
      </div>
    </div>
    <div class="controller-group">
      <%= f.label :status_id %>
      <div class='controls'>
        <%= f.collection_select :status_id, Status.all, :id, :name, { prompt: "Select a category" }, {class: "form-control" } %><br />
      </div>
    </div>
    <div class="controller-group">
      <%= f.label :issue_date %>
      <div class='controls'>
        <%= f.date_select :issue_date, class: 'form-control' %><br />
      </div>
    </div>
    <div class="controller-group">
      <%= f.label :due_date %>
      <div class='controls'>
        <%= f.date_select :due_date, class: 'form-control' %><br />
      </div>
    </div>
    <div class="form-actions clearfix">
      <span class='pull-right'>
        <%= link_to 'Back', books_path, class: 'btn btn-default' %>
        <%= f.submit class: 'btn btn-primary' %>
      </span>
    </div>
  </fieldset>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

app/views/transactions/index.html.erb
<h1>
  Listing transactions 
  <% if current_user.try(:admin?) %>
    <a href='/transactions/new' class='btn btn-default btn-sm pull-right'><span class='glyphicon glyphicon-plus'></span>&nbsp;New transaction</a>
  <% end %>
</h1>

<ul class='main-list well'>
  <% if @transactions.count == 0 %>
  <li class='row-fluid'>
    <div class='myicon'><span class='glyphicon glyphicon-info-sign red'></span>&nbsp;&nbsp;No records found</div>
  </li>
  <% end %>
  <% @transactions.each do |transaction| %>
    <li class='row-fluid'>
      <div class='myicon'> 
        <b> <%= transaction.book.title %> </b> <span class="hidden-sm hidden-md"> <%= ", Borrower: " %> <i> <%= transaction.user.email %> </i> </span> <span class="hidden-sm"> <%= "on: " + transaction.issue_date.to_s %> </span>
      </div>
      <div class='pull-right'>
        <b> <%= transaction.status.name %></b>
        <a href="<%= transaction_path(transaction) %>" class='btn btn-xs' role='button'><span class='glyphicon glyphicon-zoom-in'></span></a>
        <% if current_user.try(:admin?) %>
          <a href="<%= edit_transaction_path(transaction) %>" class='btn btn-xs'  role='button'><span class='glyphicon glyphicon-edit'></span></a>
          <a href="<%= transaction_path(transaction) %>" class='btn btn-xs btn-danger' role='button' data-confirm'Are you sure?' data-method='delete' rel='nofollow'><span class='glyphicon glyphicon-remove'></span></a>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

app/views/transactions/show.html.erb
<h1>Transaction Details
  <small class='pull-right'>
    <% if current_user.try(:admin?) %>
      <%= link_to 'Edit', edit_transaction_path(@transaction), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to "Back", transactions_path, class: 'btn btn-default' %>
  </small>
</h1>
<div class='main-list well'>
  <p>
    <strong>User:</strong>
    <%= @transaction.user.email %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @transaction.status.name %>
  </p>

  <p>
    <strong>Issue date:</strong>
    <%= @transaction.issue_date %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= @transaction.due_date %>
  </p>

<!--   <p>
    <strong>Book details:</strong>
    <a href="#" class='btn btn-default' role='button' id='show-book-info' value="<%= @transaction.book_id %>"><span class='glyphicon glyphicon-th-list'></span>&nbsp;&nbsp;Click here</a>
  </p> -->
</div>
<h1>Book Details</h1>
<div id="book-detail" class="main-list well">
  <p>
    <strong>Title:</strong>
    <%= @transaction.book.title %>
  </p>

  <p>
    <strong>Edition:</strong>
    <%= @transaction.book.edition %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= @transaction.book.isbn %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @transaction.book.author.name %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= @transaction.book.publisher.name %>
  </p>
</div>