config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'directory#index'

  get 'search/:keyword(.:format)' => 'books#search', as: 'search/'

  get 'genre_search/:keyword(.:format)' => 'books#genre_search', as: 'genre_search//'

  get 'books/ranking' => 'books#ranking'
  
  post 'rent' => 'transactions#rent'

  resources :books

  resources :authors

  resources :transactions

  resources :statuses

  resources :publishers

  resources :genres

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>Library</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
    <nav role="navigation" class="navbar navbar-inverse navbar-fixed-top navbar-shadow">
		<div class='container-fluid'>
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
	            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	            </button>
	            <a href='/' class='navbar-brand logo'>
					<img alt='Library' src='/images/logo.png'>
				</a>
	        </div>
	        <!-- Collection of nav links, forms, and other content for toggling -->
	        <div id="navbarCollapse" class="collapse navbar-collapse">
	            <ul class="nav navbar-nav">
	                <li <%= (controller.controller_name == 'directory') ? "class='active'>".html_safe : ">".html_safe %>
	                	<%= link_to 'Home', :root %></li>
	                <li <%= (controller.controller_name == 'authors') ? "class='active'>".html_safe : ">".html_safe %>
	                	<%= link_to 'Author', authors_path %></li>
		            <li <%= (controller.controller_name == 'books') ? "class='active'>".html_safe : ">".html_safe %>
		                <%= link_to 'Book', books_path %></li>
		            <% if current_user.try(:admin?) %>
		                <li <%= (controller.controller_name == 'genres') ? "class='active'>".html_safe : ">".html_safe %>
		                	<%= link_to 'Genre', genres_path %></li>
		            <% end %>
	                <li <%= (controller.controller_name == 'publishers') ? "class='active'>".html_safe : ">".html_safe %>
	                	<%= link_to 'Publisher', publishers_path %></li>
	                <% if current_user.try(:admin?) %>
		                <li <%= (controller.controller_name == 'statuses') ? "class='active'>".html_safe : ">".html_safe %>
		                	<%= link_to 'Status', statuses_path %></li>
		            <% end %>
		            <% if current_user %>
		                <li <%= (controller.controller_name == 'transactions') ? "class='active'>".html_safe : ">".html_safe %>
		                	<%= link_to 'Transaction', transactions_path %></li>
		                <li <%= (controller.controller_name == 'user') ? "class='active'>".html_safe : ">".html_safe %>
		                	<%= link_to 'Profile', edit_user_registration_path %>
		                </li>
		                <li class="dropdown">
		                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
		                    <ul role="menu" class="dropdown-menu">
		                        <li><a href="#">Inbox</a></li>
		                        <li><a href="#">Drafts</a></li>
		                        <li><a href="#">Sent Items</a></li>
		                        <li class="divider"></li>
		                        <li><a href="#">Trash</a></li>
		                    </ul>
		                </li>
	                <% end %>
	            </ul>
	            <div role="search" class="navbar-form navbar-left">
	                <div class="form-group">
	                    <span class='glyphicon glyphicon-search white'></span>&nbsp;
	                    <% if (controller.controller_name == 'books' && ( controller.action_name == 'genre_search' || controller.action_name == 'search' )) %>
	                    	<input id="on-search-page" type="text" placeholder="Search" class="form-control">
	                    <% else %>
	                    	<input id="off-search-page" type="text" placeholder="Search" class="form-control">
	                    <% end %>
	                </div>
	            </div>
	            <ul class="nav navbar-nav navbar-right">
	            	<% if current_user %>
	            		<li>
	            			<%= content_tag :a, href: edit_user_registration_path do %>
	            				<span class='glyphicon glyphicon-user white'></span>&nbsp;<%= current_user.email %>
	            			<% end %>
	            		</li>
	            		<li>
	            			<%= content_tag :a, href: destroy_user_session_path, data: { method: 'delete' } do %>
	            				<span class='glyphicon glyphicon-off white'></span>&nbsp;Sign out
	            			<% end %>
	            		</li>
	            	<% else %>
		                <li>
	            			<%= content_tag :a, href: new_user_session_path do %>
	            				<span class='glyphicon glyphicon-lock white'></span>&nbsp;Sign in
	            			<% end %>
	            		</li>
		                <li>
	            			<%= content_tag :a, href: new_user_registration_path do %>
	            				<span class='glyphicon glyphicon-pencil white'></span>&nbsp;Sign up
	            			<% end %>
	            		</li>
		            <% end %>
	            </ul>
	        </div>
	    </div>
    </nav>
    <div class="row">
	  	<div class="col-sm-2">
			<div class="sidebar-nav">
				<div class="navbar navbar-inverse" role="navigation">
					<div class="navbar-header">
					  	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
						    <span class="sr-only">Toggle navigation</span>
						    <span class="icon-bar"></span>
						    <span class="icon-bar"></span>
						    <span class="icon-bar"></span>
					  	</button>
					  	<span class="visible-xs navbar-brand">Sidebar menu</span>
					</div>
					<div class="navbar-collapse collapse sidebar-navbar-collapse">
					  	<ul class="genre-list nav navbar-nav">
					  		<li><a href="<%= books_path %>/ranking">Most popular&nbsp;&nbsp;<span class="badge"><%= Book.count.to_s %></span></a></li>
						  	<li class="active"><a href="#" class="<%= (controller.controller_name == 'books' && ( controller.action_name == 'genre_search' || controller.action_name == 'search' )) ? 'on' : 'off' %>-genre-search-page"><span id='clicked-genre'>All</span>&nbsp;&nbsp;<span class="badge"><%= Book.count.to_s %></span></a></li>
						  	<% Genre.all.each do |g| %>
					      		<li class="active"><a href="#" class="<%= (controller.controller_name == 'books' && ( controller.action_name == 'genre_search' || controller.action_name == 'search' )) ? 'on' : 'off' %>-genre-search-page"><span id='clicked-genre'><%= g.name %></span>&nbsp;&nbsp;<span class="badge"><%= Book.where("genre_id = ?", g.id).count %></span></a></li>
					      	<% end %>
					    	<li><a href="#">Reviews&nbsp;&nbsp;<span class="badge">1,118</span></a></li>
					  	</ul>
					</div><!--/.nav-collapse -->
					</div>
				</div>
		  	</div>
			<div class="col-sm-10">
				<div class='container-fluid'>
					<% flash.each do |name, msg| %>
						<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
							<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<%= content_tag :div, msg, :id => "flash_#{name}" %>
						</div>
					<% end %>
					<%= yield %>
				</div>
			</div>
		</div> 
			
	</body>
</html>